// WHY: the UI authoring guidance is the bridge between the static phantom-*
// vocabulary on disk (public/_base.html, public/_components.html, the
// _examples reference pages) and the live agent's runtime authoring behavior.
// It lives in its own module so prompt-assembler.ts stays small and so the
// Project 2 research can be re-applied as a single edit without touching the
// surrounding scaffold.

export function buildUIGuidanceLines(publicUrl: string | undefined): string[] {
	const lines: string[] = [];
	lines.push("");
	lines.push("=== UI PAGE AUTHORING ===");
	lines.push("");
	lines.push("You can create web pages and serve them on your domain at /ui/<path>.");
	lines.push("The authoring model is simple: you write HTML, the base template wraps it,");
	lines.push("the page renders behind magic-link cookie auth.");
	lines.push("");
	lines.push("PHILOSOPHY.");
	lines.push("You are authoring surfaces for the operator who owns this agent. Every");
	lines.push("page you create is part of that operator's product experience. The");
	lines.push("aesthetic bar is Linear, Anthropic Console, and Notion. Not Bootstrap");
	lines.push("and not Shadcn and not a generic Tailwind admin template.");
	lines.push("");
	lines.push("You are free to write any HTML you want. The design system below is");
	lines.push("reference material, not rails. When you reach for a pattern that");
	lines.push("already exists in the vocabulary, use the vocabulary class. When the");
	lines.push("page needs something unique, write bespoke HTML freehand using the");
	lines.push("tokens. Raise the floor, touch the ceiling.");
	lines.push("");
	lines.push("THE BASE TEMPLATE.");
	lines.push("public/_base.html declares every token and every phantom-* vocabulary");
	lines.push("class. When you call phantom_create_page with title+content, the content");
	lines.push("is wrapped in this template and inherits everything for free. You do not");
	lines.push("redeclare CSS. You do not import fonts. You do not register chart themes.");
	lines.push("You just write HTML that uses the class names.");
	lines.push("");
	lines.push("THE STYLE GUIDE.");
	lines.push("/ui/_components.html renders every vocabulary class with a label in");
	lines.push("both light and dark themes. When you forget what a pattern looks like,");
	lines.push("open this file with Read. It is the closest thing to a Figma library file");
	lines.push("you have. Reach for it before guessing.");
	lines.push("");
	lines.push("REFERENCE EXAMPLES.");
	lines.push("public/_examples/01-landing.html through 10-chat-active.html are ten");
	lines.push("complete reference compositions. Open them with Read when you want to");
	lines.push("remember how a dashboard, a session history table, an evolution timeline,");
	lines.push("a memory explorer, a skills editor, a cost report, or a chat surface");
	lines.push("is composed from the vocabulary. They are taste calibration, not rails.");
	lines.push("");
	lines.push("THE VOCABULARY, GROUPED BY CATEGORY.");
	lines.push("");
	lines.push("Layout primitives: phantom-page (max 1240px), phantom-page-narrow (760px),");
	lines.push("  phantom-section, phantom-row, phantom-col,");
	lines.push("  phantom-grid-stats (4-col responsive), phantom-grid-main-side (2/3+1/3),");
	lines.push("  phantom-grid-cards (auto-fill 280px), phantom-divider.");
	lines.push("");
	lines.push("Typography: phantom-display (Instrument Serif 40-60px clamp, italic via <em>),");
	lines.push("  phantom-h1 (serif 32px), phantom-h2 (serif 22px),");
	lines.push("  phantom-h3 (Inter 14px weight 600),");
	lines.push("  phantom-eyebrow (uppercase tracked label above titles),");
	lines.push("  phantom-lead (opening paragraph), phantom-body (standard 14px body),");
	lines.push("  phantom-muted (color modifier), phantom-mono (JetBrains Mono),");
	lines.push("  phantom-meta (metadata timestamps).");
	lines.push("");
	lines.push("Cards and stats: phantom-card (1px border, 14px radius, no default shadow),");
	lines.push("  phantom-card-compact, phantom-card-hover,");
	lines.push("  phantom-stat, phantom-stat-label, phantom-stat-value,");
	lines.push("  phantom-stat-trend-up/-down/-flat.");
	lines.push("");
	lines.push("Tables (always tabular numerics): phantom-table, phantom-table-compact.");
	lines.push("");
	lines.push("Badges, chips, dots, status: phantom-badge with variants");
	lines.push("  -primary/-success/-warning/-error/-info/-neutral,");
	lines.push("  phantom-chip (togglable with aria-pressed),");
	lines.push("  phantom-dot, phantom-dot-live (pulsing),");
	lines.push("  phantom-dot-success/-warning/-error/-info.");
	lines.push("");
	lines.push("Timeline, empty, skeleton: phantom-timeline, phantom-timeline-item");
	lines.push("  with -time/-title/-body slots, phantom-empty with -icon/-title/-body,");
	lines.push("  phantom-skeleton (shimmer loading placeholder).");
	lines.push("");
	lines.push("Forms, buttons, alerts: phantom-form-row, phantom-label,");
	lines.push("  phantom-input, phantom-textarea, phantom-select (3px focus ring),");
	lines.push("  phantom-button (pill), phantom-button-primary (indigo fill),");
	lines.push("  phantom-button-ghost (outlined), phantom-button-danger (red),");
	lines.push("  phantom-button-sm (compact),");
	lines.push("  phantom-alert with -success/-error/-warning/-info variants,");
	lines.push("  phantom-toast (floating notification).");
	lines.push("");
	lines.push("Modals, sheets, nav, tabs: phantom-modal-backdrop, phantom-modal,");
	lines.push("  phantom-sheet, phantom-nav, phantom-nav-brand, phantom-nav-item,");
	lines.push("  phantom-breadcrumb, phantom-tabs, phantom-tab (aria-selected active).");
	lines.push("");
	lines.push("Chat (used by Project 4 web chat): phantom-chat-thread,");
	lines.push("  phantom-chat-bubble-user, phantom-chat-bubble-assistant,");
	lines.push("  phantom-chat-tool-card, phantom-chat-thinking.");
	lines.push("");
	lines.push("Charts (use the helper): phantom-chart (320px), phantom-chart-sm (160px),");
	lines.push("  phantom-chart-lg (480px).");
	lines.push("  Always init via window.phantomChart(element, option). The helper reads");
	lines.push("  the current theme, registers, resizes, and re-inits on theme toggle.");
	lines.push("  Reduces chart boilerplate from ~20 lines to 3.");
	lines.push("");
	lines.push("TOKENS YOU REFERENCE.");
	lines.push("Colors: --color-base-100 (page background), --color-base-200 (card surface),");
	lines.push("  --color-base-300 (border), --color-base-content (primary text),");
	lines.push("  --color-primary (indigo accent),");
	lines.push("  --color-success/-warning/-error/-info (status accents).");
	lines.push("Spacing (4px ladder): --space-1 through --space-16.");
	lines.push("Radii: --radius-sm 8, -md 10, -lg 14, -xl 20, -pill 9999.");
	lines.push("Motion: --motion-fast 100ms, -base 150ms, -slow 300ms.");
	lines.push("Easing: --ease-out is cubic-bezier(0.25, 0.46, 0.45, 0.94).");
	lines.push("");
	lines.push("FONTS. Inter for body and UI. Instrument Serif for display, h1, h2 (italic");
	lines.push("via <em> reads as editorial, not decorative). JetBrains Mono for code,");
	lines.push("timestamps, and tabular metadata.");
	lines.push("");
	lines.push("TASTE CALIBRATION.");
	lines.push("");
	lines.push("One. Make every dashboard as dense and crisp as Linear, as restrained as");
	lines.push("Anthropic Console, as typographically clean as Notion, and as numerically");
	lines.push("tabular as Stripe. You are building an operator tool. Serious and quiet.");
	lines.push("");
	lines.push("Two. When you use a stat card, pair the value with a trend indicator.");
	lines.push("A bare number is prototype energy.");
	lines.push("");
	lines.push("Three. Tabular numerics everywhere numbers appear. The body default");
	lines.push("already has font-variant-numeric: tabular-nums. Do not override it.");
	lines.push("");
	lines.push("Four. Use window.phantomChart(el, option) instead of raw echarts.init.");
	lines.push("Keep charts to 1-2 per page.");
	lines.push("");
	lines.push("Five. When in doubt, open /ui/_components.html with Read and look at");
	lines.push("how the pattern you need is already rendered. The style guide is your memory.");
	lines.push("");
	lines.push("NON-NEGOTIABLES.");
	lines.push("No em dashes in body text. No emojis. No hardcoded hex colors (use var()).");
	lines.push("No bg-primary/10 slash opacity in text/tailwindcss blocks (parser bug).");
	lines.push("  Use color-mix(in oklab, var(--color-primary) 10%, transparent) instead.");
	lines.push("No <script> tags inside <main>. CDN scripts in <head>, app scripts at");
	lines.push("  the bottom of <body>. No transition: all. No shadow on default cards.");
	lines.push("");
	lines.push("PAGE MODE. For simple pages: phantom_create_page with title+content.");
	lines.push("For pages with charts or diagrams: phantom_create_page with the html");
	lines.push("parameter. Copy the base template head so fonts and tokens are inherited.");
	lines.push("");
	lines.push("ALWAYS VALIDATE. After phantom_create_page succeeds, always call");
	lines.push("phantom_preview_page with the same path. Review the screenshot. Read the");
	lines.push("JSON metadata block. If console.errors > 0 or network.failedRequests > 0,");
	lines.push("fix the HTML and re-preview until both are zero. Only then report the page.");
	lines.push("");
	if (publicUrl) {
		lines.push(`Pages are at ${publicUrl}/ui/<filename>`);
	}
	return lines;
}
